from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Blog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)
    url = db.Column(db.String(255), nullable=False)
    location = db.Column(db.String(255))
    child_id = db.Column(db.String(255))
    blog_type = db.Column(db.String(50))
    original_blog_type = db.Column(db.String(50))
    version = db.Column(db.String(50))
    description = db.Column(db.Text)
    title = db.Column(db.String(255))
    last_id = db.Column(db.BigInteger)
    notes = db.Column(db.Text)
    tags = db.Column(db.Text)
    rating = db.Column(db.Integer, default=0)
    total_count = db.Column(db.Integer, default=0)
    posts = db.Column(db.Integer, default=0)
    texts = db.Column(db.Integer, default=0)
    answers = db.Column(db.Integer, default=0)
    quotes = db.Column(db.Integer, default=0)
    photos = db.Column(db.Integer, default=0)
    number_of_links = db.Column(db.Integer, default=0)
    conversations = db.Column(db.Integer, default=0)
    videos = db.Column(db.Integer, default=0)
    audios = db.Column(db.Integer, default=0)
    photo_metas = db.Column(db.Integer, default=0)
    video_metas = db.Column(db.Integer, default=0)
    audio_metas = db.Column(db.Integer, default=0)
    downloaded_texts = db.Column(db.Integer, default=0)
    downloaded_quotes = db.Column(db.Integer, default=0)
    downloaded_photos = db.Column(db.Integer, default=0)
    downloaded_links = db.Column(db.Integer, default=0)
    downloaded_answers = db.Column(db.Integer, default=0)
    downloaded_conversations = db.Column(db.Integer, default=0)
    downloaded_videos = db.Column(db.Integer, default=0)
    downloaded_audios = db.Column(db.Integer, default=0)
    downloaded_photo_metas = db.Column(db.Integer, default=0)
    downloaded_video_metas = db.Column(db.Integer, default=0)
    downloaded_audio_metas = db.Column(db.Integer, default=0)
    duplicate_photos = db.Column(db.Integer, default=0)
    duplicate_videos = db.Column(db.Integer, default=0)
    duplicate_audios = db.Column(db.Integer, default=0)
    download_text = db.Column(db.Boolean, default=False)
    download_quote = db.Column(db.Boolean, default=False)
    download_photo = db.Column(db.Boolean, default=True)
    download_link = db.Column(db.Boolean, default=False)
    download_answer = db.Column(db.Boolean, default=False)
    download_conversation = db.Column(db.Boolean, default=False)
    download_video = db.Column(db.Boolean, default=True)
    download_audio = db.Column(db.Boolean, default=True)
    create_photo_meta = db.Column(db.Boolean, default=False)
    create_video_meta = db.Column(db.Boolean, default=False)
    create_audio_meta = db.Column(db.Boolean, default=False)
    download_replies = db.Column(db.Boolean, default=False)
    download_reblogged_posts = db.Column(db.Boolean, default=False)
    download_url_list = db.Column(db.Boolean, default=False)
    dump_crawler_data = db.Column(db.Boolean, default=False)
    reg_ex_photos = db.Column(db.Boolean, default=False)
    reg_ex_videos = db.Column(db.Boolean, default=False)
    skip_gif = db.Column(db.Boolean, default=False)
    download_video_thumbnail = db.Column(db.Boolean, default=False)
    force_size = db.Column(db.Boolean, default=False)
    force_rescan = db.Column(db.Boolean, default=False)
    check_directory_for_files = db.Column(db.Boolean, default=False)
    group_photo_sets = db.Column(db.Boolean, default=False)
    save_texts_individual_files = db.Column(db.Boolean, default=False)
    zip_crawler_data = db.Column(db.Boolean, default=False)
    download_imgur = db.Column(db.Boolean, default=False)
    download_webmshare = db.Column(db.Boolean, default=False)
    download_uguu = db.Column(db.Boolean, default=False)
    download_cat_box = db.Column(db.Boolean, default=False)
    webmshare_type = db.Column(db.String(50))
    uguu_type = db.Column(db.String(50))
    cat_box_type = db.Column(db.String(50))
    pnj_download_format = db.Column(db.String(50))
    metadata_format = db.Column(db.String(50))
    download_pages = db.Column(db.String(255))
    page_size = db.Column(db.Integer, default=50)
    download_from = db.Column(db.String(255))
    download_to = db.Column(db.String(255))
    password = db.Column(db.String(255))
    filename_template = db.Column(db.String(255), default="%f")
    date_added = db.Column(db.DateTime)
    last_complete_crawl = db.Column(db.DateTime)
    latest_post = db.Column(db.DateTime)
    online = db.Column(db.Boolean, default=False)
    settings_tab_index = db.Column(db.Integer, default=0)
    progress = db.Column(db.Integer, default=0)
    collection_id = db.Column(db.Integer, default=0)
    status = db.Column(db.String(50), default='idle') # idle, crawling, finished, error

    files = db.relationship('File', backref='blog', lazy=True, cascade="all, delete-orphan")

class File(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    blog_id = db.Column(db.Integer, db.ForeignKey('blog.id'), nullable=False)
    link = db.Column(db.Text, nullable=False)
    original_link = db.Column(db.Text)
    filename = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), default='active', nullable=False)  # active, archived, deleted
