CREATE TABLE blogs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(2083) NOT NULL,
    location VARCHAR(255),
    child_id VARCHAR(255),
    blog_type VARCHAR(50),
    original_blog_type VARCHAR(50),
    version VARCHAR(10),
    description TEXT,
    title TEXT,
    tags TEXT,
    notes TEXT,
    password VARCHAR(255),
    filename_template VARCHAR(255),
    file_download_location VARCHAR(255),
    last_downloaded_photo VARCHAR(255),
    last_downloaded_video VARCHAR(255),
    download_pages VARCHAR(255),
    download_from VARCHAR(255),
    download_to VARCHAR(255),
    pnj_download_format VARCHAR(10),
    rating INT,
    duplicate_photos INT,
    duplicate_videos INT,
    duplicate_audios INT,
    total_count INT,
    posts INT,
    texts INT,
    answers INT,
    photos INT,
    number_of_links INT,
    conversations INT,
    videos INT,
    audios INT,
    photo_metas INT,
    video_metas INT,
    audio_metas INT,
    downloaded_texts INT,
    downloaded_quotes INT,
    downloaded_photos INT,
    downloaded_links INT,
    downloaded_answers INT,
    downloaded_conversations INT,
    downloaded_videos INT,
    downloaded_audios INT,
    downloaded_photo_metas INT,
    downloaded_video_metas INT,
    downloaded_audio_metas INT,
    page_size INT,
    settings_tab_index INT,
    progress INT,
    collection_id INT,
    downloaded_items_new INT,
    last_id BIGINT UNSIGNED,
    date_added DATETIME,
    last_complete_crawl DATETIME,
    latest_post DATETIME,
    download_text BOOLEAN,
    download_quote BOOLEAN,
    download_photo BOOLEAN,
    download_link BOOLEAN,
    download_answer BOOLEAN,
    download_conversation BOOLEAN,
    download_video BOOLEAN,
    download_audio BOOLEAN,
    create_photo_meta BOOLEAN,
    create_video_meta BOOLEAN,
    create_audio_meta BOOLEAN,
    download_replies BOOLEAN,
    download_reblogged_posts BOOLEAN,
    dump_crawler_data BOOLEAN,
    reg_ex_photos BOOLEAN,
    reg_ex_videos BOOLEAN,
    check_directory_for_files BOOLEAN,
    download_url_list BOOLEAN,
    skip_gif BOOLEAN,
    download_video_thumbnail BOOLEAN,
    force_size BOOLEAN,
    force_rescan BOOLEAN,
    group_photo_sets BOOLEAN,
    save_texts_individual_files BOOLEAN,
    zip_crawler_data BOOLEAN,
    online BOOLEAN,
    download_imgur BOOLEAN,
    download_webmshare BOOLEAN,
    download_uguu BOOLEAN,
    download_catbox BOOLEAN,
    webmshare_type VARCHAR(50),
    uguu_type VARCHAR(50),
    catbox_type VARCHAR(50),
    states VARCHAR(50),
    metadata_format VARCHAR(50)
);

CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    blog_id INT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    url VARCHAR(2083),
    timestamp DATETIME,
    FOREIGN KEY (blog_id) REFERENCES blogs(id)
);
